### ISSUE TITLE
Loading imag preload

### ISSUE THREAD

**Issue by guox191** [ElemeFE/vue-img#1]
在较差的网络环境下，由于 loading image 是在第一个 `directive` 出现时开始加载的，会出现空白的 `<img />`，后显示 `loading page`，之后显示目标。
在整个应用中使用同一张 loading image，在 `directive`出现前预加载，并大小相同?

**Comment by banricho** [comment]
使用指令的话，肯定要等到 Vue 扫描绑定完节点才可以，而且肯定在流程控制 `v-if` `v-for` 指令之后。。。

理论上可以直接先给 `<img>` 设置 `src` 属性，这个优先级肯定高于指令。等指令拿到对应的图片加载上去的时候，会覆盖那个 `src`。试试吧~

**Comment by guox191** [comment]
#2
